### ISSUE TITLE
Ruby Library

### ISSUE THREAD

**Issue by ankane** [david-cortes/isotree#12]
Hi David, I came across your work last week and am a big fan of a number of your projects!

I wanted to let you know I created a [Ruby library](https://github.com/ankane/isotree) for IsoTree. It's fairly basic right now (only supports numeric data and has a limited number of methods and options) and follows the Python API. If you have any feedback, let me know or feel free to create an issue on the project. Thanks!

**Comment by david-cortes** [comment]
Great, thanks! I'll add a link in the readme.

I unfortunately don't know ruby and would have no clue about how to test it, so cannot provide any feedback. Only would like to ask if the Numo::Narray that you are using there uses or casts the input data to column-major order, as it seems to closely follow numpy's design which by default uses row-major order.

**Comment by ankane** [comment]
Thanks @david-cortes, I missed that. I've added more tests to make sure the output matches exactly. Thanks for adding it to the readme!
