### ISSUE TITLE
Trapped signals

### ISSUE THREAD

**Issue by ankane** [david-cortes/isotree#13]
Hi David, it looks like running `fit_iforest` adds a signal handler that causes signals to be ignored. You can test it out with a basic Flask app.

```python
from flask import Flask
import numpy as np
from isotree import IsolationForest
app = Flask(__name__)

@app.route('/')
def hello_world():
    X = np.random.normal(size = (100, 2))
    iso = IsolationForest(ntrees = 10, ndim = 2, nthreads = 1)
    iso.fit(X)
    return 'Hello, World!'
```

Start the server and visit the page. When trying to exit with ctrl+C, it prints:

```txt
^CError: procedure was interrupted
^CError: procedure was interrupted
^CError: procedure was interrupted
^CError: procedure was interrupted
^CError: procedure was interrupted
```

**Comment by ankane** [comment]
Thanks for trying out a few approaches. The commit above is definitely an improvement (but still traps the signal even when `fit_iforest` isn't running). For the Ruby library, I've removed the signal handling for now so it doesn't cause issues with web servers.

Based on the above, it seems like adding a method to fit each tree like XGBoost and LightGBM and avoiding signal handling is likely the cleanest method, but I totally understand if it's not something you'd like to add right now.

**Comment by david-cortes** [comment]
I'm finding out this causes more hassle than I expected so for version 0.1.24 it now has an additional argument `handle_interrupt` to control whether or not to do this at the C++ level.

**Comment by ankane** [comment]
Great, thanks @david-cortes. Will retire my fork for the Ruby gem.

**Comment by david-cortes** [comment]
I just realized that when calling the C function `signal` it returns the current signal handler. This was a really stupid bug.

**Comment by ankane** [comment]
Looks much cleaner. I think the `handle_interrupt` option would still be useful to avoid trapping signals on web servers, fwiw.

**Comment by david-cortes** [comment]
@ankane But the signals aren't trapped now - if you try it with flask, it will stop successfully with Ctrl + C, and before exit it restores the signal handler that was there when the function was called. Also it throws an exception when it gets interrupted.

**Comment by ankane** [comment]
My bad, missed that it still propagates. Just tested and works great now. Well done, and thanks!

**Comment by david-cortes** [comment]
@ankane Could you try again with the last commit (https://github.com/david-cortes/isotree/commit/09bace27985f5a563067d2ce46b8e89febf7833d)?

**Comment by david-cortes** [comment]
Finally found a way to make it safely propagate the signal to the original signal handler as if it never were trapped. In the C++ and R versions, it will however throw an exception if it receives a SIGINT, so please add `#define DONT_THROW_ON_INTERRUPT` is  that problematic (e.g. the python process terminates when it encounters a C++ exception, whereas the R one only stops the current function).

**Comment by ankane** [comment]
Great, both 0.1.28 and master seem to stop immediately and propagate the signal. Thanks!
