### ISSUE TITLE
Connection Lost

### ISSUE THREAD

**Issue by tenshis** [david-cortes/isotree#20]
Whenever I try to train the model in R, my session is restarted without any further info:

```
[Info] Connection Lost
[Info] Restarting R...
```

**Comment by david-cortes** [comment]
Please provide more information:
* What kind of system are you running this on (e.g. operating system, R version, is it a regular desktop).
* How are you creating the model (which arguments are you passing, in which format is the data, which kind of columns it contains, how many rows and columns).
* Where are you seeing that message.

A reproducible example would help.

**Comment by david-cortes** [comment]
Also, if you're using the default arguments, I'd venture to say that you're probably running out of RAM and your R process is getting killed by the operating system.
