### ISSUE TITLE
New Functions in R package version 0.1.24 not visible

### ISSUE THREAD

**Issue by veeveetran** [david-cortes/isotree#21]
Hi David,

I updated the package to make sure that I had the latest version of isotree in R. However, the following functions don't show up when I try to call them:
- predict.isolation_forest
- print.isolation_forest
- summary.isolation_forest

The error I receive is: ` Error: 'summary.isolation_forest' is not an exported object from 'namespace:isotree'`

Is there anything I need to do in addition to updating the package?

Thanks!

(P.S. love this package by the way. It is been extremely useful and informative)

**Comment by david-cortes** [comment]
Well indeed, those are S3 methods, so you don't call them with the full name, you call them like `print(model)`.

**Comment by veeveetran** [comment]
Got it! Thank you for the clarification. Much appreciated.
