### ISSUE TITLE
Question on the anomaly score result: which column (attribute) contributes the most?

### ISSUE THREAD

**Issue by Shea1986** [david-cortes/isotree#35]
Great work on isotree. May I ask you a question? Is there a way to tell which column or columns contributes the most to the high anomaly score, in high dimensional data? It would be tremendously helpful in medical fields.

**Comment by david-cortes** [comment]
There's no such functionality in this package but you can use black-box prediction explainers from other libraries based on e.g. SHAP or local sensitivity.
