### ISSUE TITLE
Question: When categorical attributes are split into subsets, are the subsets random?

### ISSUE THREAD

**Issue by krishnangovindraj** [david-cortes/isotree#37]
Sorry for the likely stupid question but I can't seem to figure it out from the code or anywhere else.

When `categ_split_type == Subset`, If a certain categorical attribute is chosen for the split, is the subset computed randomly each time? (I imagine it is, but I just needed to confirm)

Thanks!

**Comment by david-cortes** [comment]
If you do not pass any gain-related parameters and do not change other parameters that would make it less random, then yes, that's how it should work.

**Comment by krishnangovindraj** [comment]
Thanks!
