### ISSUE TITLE
Training Isotree with Python on Windows then Deserializing with C++ on Raspberry Pi 3B+ (Linux)

### ISSUE THREAD

**Issue by hmcd7** [david-cortes/isotree#49]
I am trying to serialize the model from example one of isotree_example.ipynb on a Windows system, then deserialize it using C++ on the Raspberry Pi 3B+ with a Linux OS but I am encountering some problems. 

The model was serialized using the export_model method with add_metadata_file set to false.
![image](https://github.com/david-cortes/isotree/assets/134107404/c2d89cb9-ae71-43aa-a171-25661c0002e3)

The main file being executed is isotree_demo.cpp (shown below) which simply tries to deserialize the model.

![image](https://github.com/david-cortes/isotree/assets/134107404/f90d2375-f4de-48db-a153-76da23d36229)

Before deserializing with deserialize_combined, the model is checked with inspect_serialized_object which gives the following values:
![image](https://github.com/david-cortes/isotree/assets/134107404/712f269c-d15e-453f-b238-ab67b5f056dd)

Running isotree_demo led to an "unexpected error" in serialize.cpp in the deserialize_model function:
![image](https://github.com/david-cortes/isotree/assets/134107404/34a0d4cd-a06f-4a38-bada-e6aafdfa4683)

In an attempt to debug, I printed the values being checked by the deserialize_model function:
![image](https://github.com/david-cortes/isotree/assets/134107404/c4642cf1-4301-4170-a4c6-bf47071a8695)

I am unsure why saved_int_t and saved_size_t are being set to the PlatformSize enum value 4 (Other) when the Raspberry Pi 3B+ is 32bit. 

I attempted to force the 32bit check to true as shown in the screenshot below, but this caused a segmentation fault.
![image](https://github.com/david-cortes/isotree/assets/134107404/1cd9f1ce-7852-4d53-80a7-11b0f2d151ca)

Any suggestions would be appreciated.

**Comment by david-cortes** [comment]
Thanks for the detailed bug report. There's indeed something going wrong when you saved the model on windows, as it should have values 2 and 3 for int_t and size_t, respectively.

A couple questions:
* What compiler did you use to build the library for windows?
* Just to make sure - are you using the latest version of this library in both windows and the raspberry machine?
* Do you observe the same kind of error if you save the model from the R version (from CRAN) of this library in windows? This snippet should do the same thing:
```r
library(isotree)
set.seed(1)
m <- 100
n <- 2
X <- matrix(rnorm(m * n), nrow = m)
X <- rbind(X, c(3, 3))
iso <- isolation.forest(X, ntrees = 10, nthreads = 1)
isotree.export.model(
    iso,
    "C:\\Users\\e40027094\\Desktop\\isotree_R_model.bin",
    add_metadata_file = TRUE
)
```

**Comment by david-cortes** [comment]
Actually I just realized there's a bug in the de-serialization. I've pushed a fix under branch `alt_int_size` - could you try using that branch in the C++ raspberry platform?
```shell
git clone http://github.com/david-cortes/isotree.git
cd isotree
mkdir build
cd build
cmake ..
make
```

**Comment by david-cortes** [comment]
> Thank you, I've made those corrections but it unfortunately still crashes. Here is the bin file. Thank you. [isotree_model.zip](https://github.com/david-cortes/isotree/files/11536674/isotree_model.zip)

Thanks. So it seems there's a bug with the model adding metadata when it shouldn't. Nevertheless, it's still possible to load this file if you allocate a buffer for the metadata from the `inspect_serialized_object` outputs.

The following works for me if you pull the latest commit from the master branch - could you give it a try?
```cpp
#include "isotree.hpp"
#include <stdio.h>
#include <memory>

int main()
{
    ExtIsoForest model_ext;
    FILE *fin = fopen("isotree_model.bin", "r");

    bool is_isotree_model;
    bool is_compatible;
    bool has_combined_objects;
    bool has_IsoForest;
    bool has_ExtIsoForest;
    bool has_Imputer;
    bool has_Indexer;
    bool has_metadata;
    size_t size_metadata;
    inspect_serialized_object(
        fin,
        is_isotree_model,
        is_compatible,
        has_combined_objects,
        has_IsoForest,
        has_ExtIsoForest,
        has_Imputer,
        has_Indexer,
        has_metadata,
        size_metadata
    );
    std::unique_ptr<char[]> buffer(new char[size_metadata]);


    deserialize_combined(
        fin,
        nullptr,
        &model_ext,
        nullptr,
        nullptr,
        buffer.get()
    );
    double Xnew[] = {1., 1.};
    double odepth;
    predict_iforest(
        Xnew, nullptr,
        false, 2, 0,
        nullptr, nullptr, nullptr,
        nullptr, nullptr, nullptr,
        1, 1, true,
        nullptr, &model_ext,
        &odepth, nullptr,
        nullptr,
        nullptr
    );
    std::cout << "score:" << odepth << std::endl;
    return 0;
}
```

**Comment by hmcd7** [comment]
Thank you very much, that worked for me as well.
