### ISSUE TITLE
Using with python3.8 and numpy==1.24.4

### ISSUE THREAD

**Issue by MikeMACintosh** [david-cortes/isotree#54]
Thanks for great work!
Is it possible to use this project with python3.8 and numpy 1.24.4?

I have error when I try to install latest isotree versions in this config.

Thank you,
Mike

**Comment by david-cortes** [comment]
I guess it should be be possible, but cannot tell for sure. You'll need to create your own wheel bypassing the build environment used here though - you can google about it for more info.
