### ISSUE TITLE
About missing_action

### ISSUE THREAD

**Issue by pholiu** [david-cortes/isotree#63]
Just to clarify, does the "divide" option in missing_action argument just treat the missing values as another branch during splitting? Is there any imputation method applied in the process for divide option? 

For "failure" option, can we understand that it just ignores the missing values and use non-missing values in the data for modeling? How different is the "failure" option from the "divide" option?

**Comment by david-cortes** [comment]
Thanks again for bringing this up. I've pushed another update to the docs - please let me know if it's still unclear after the last changes.

**Comment by pholiu** [comment]
Hi David,

I don't want to make this complicated. I didn't go through all your code
(needs lots of time) but just want to make sure that you didn't do any
imputation-related procedure for the single-variable model ("divide"
option), which is different from the "impute" option for the extended
model. Is that correct? My understanding is that you just treat the missing
values as certain values for fitting. If that is the case, I don't
understand how different it is from the "failure" option. Could you just
clarify these via email or on the Github Issue page? (Please don't just
update the documents because my questions are specific.)

Thank you for your patience and time.

Best,
Dan

**Comment by david-cortes** [comment]
> just want to make sure that you didn't do any
imputation-related procedure for the single-variable model

That is correct: there's no imputation in the single-variable model.

> My understanding is that you just treat the missing
values as certain values for fitting.

No, they are not treated as a particular value, they are treated as if they were sent into either branch of a split with a probability given by the fraction of the non-missing values that are sent to each branch.

> how different it is from the "failure" option.

In the "failure" case, different things can happen when missing values are encountered: (a) it might throw an error; (b) the program might crash; (c) missing values might be sent to the right branch of every split; (d) missing values might be removed. Which of those happens is deterministic, but depends on a series of conditions - "failure" is not meant  for cases when your data has missing values, so even if it doesn't error out, results are not mean to reflect a "correct" handling  of them.

**Comment by david-cortes** [comment]
> I would understand that the "divide" option keeps the missing values
and still uses them as a branch in the tree splitting

No. It uses them, but doesn't create any special branch for them.

> can I confirm whether the random forest is employed to grow the trees
in the isolation forest?

Not sure what you mean. You can take a look at the default values for other parameters of randomness and subsampling to make sure.

**Comment by david-cortes** [comment]
I still don't get your question, but there's a readme at the top of this repository with information and reference articles that you can check if needed.
