### ISSUE TITLE
sample_size in isolation.forest

### ISSUE THREAD

**Issue by franci2312** [david-cortes/isotree#64]
Hello, 

unfortunately, when using `isolation.forest` the following is always returned:

**'sample_size' is set to the maximum when producing scores while fitting a model**

This occurs both when I specify `sample_size` and when my dataset contains significantly more rows than 10000.

Thank you for your attention to this matter.

**Comment by david-cortes** [comment]
Thanks for raising this issue.

Just to be sure: is this about the R function `isolation.forest`? If so, are you able to provide an example where this happens?

**Comment by franci2312** [comment]
Yes, it is about the R function `isolation.forest`. 
For instance, both when fitting
`isotree::isolation.forest(df, sample_size = 2048, ntrees = 200, output_score = T)` 
and
`isotree::isolation.forest(df, ntrees = 200, output_score = T)`
I got the warning message and `nrow(dataset)` is used as sample size. However, my dataset contains 60000 rows. 

This does not happen when `output_score = F`.

**Comment by david-cortes** [comment]
That is the expected behavior according to the docs:
![image](https://github.com/user-attachments/assets/c3a9d516-97b4-4e87-9dee-dd60325d0dc4)

If you want to get predictions from a sub-sampled model, you'll first need to build the model with `output_score=FALSE` and then call `predict` on it.
