### ISSUE TITLE
Both cross_validate and GridSearchCV failed for 'Comparing Isolation Forest implementations'

### ISSUE THREAD

**Issue by jrwells-research** [david-cortes/isotree#66]
At the start of the experiments:

From 'In [4]:'

```
cv_res = cross_validate(IsolationForestIsoTree(), X, y, scoring="roc_auc",
                        cv=StratifiedKFold(n_splits=10, shuffle=True, random_state=1))

```

and 'In [5]:'

```
cv_model = GridSearchCV(estimator=IsolationForestIsoTree(ntrees=100, ndim=2,
                                                         missing_action="fail",
                                                         random_seed=1),
                        param_grid=params_try,
                        scoring="roc_auc", refit=True,
                        cv=StratifiedKFold(n_splits=10, shuffle=True, random_state=1))

```

Both failed with the following error:

`ValueError: IsolationForest should either be a classifier to be used with response_method=decision_function or the response_method should be 'predict'. Got a regressor with response_method=decision_function instead.
`

I did find a solution by changing 'scoring="roc_auc"' to 'scoring=roc_auc_fixed' where 'roc_auc_fixed' is a variable declared as follows:

`roc_auc_fixed = make_scorer(roc_auc_score, response_method="predict")`

Looking at the class declaration and wondering if it should use the following:

`class IsolationForest(OutlierMixin, BaseEstimator):
`

or

`class IsolationForest(ClassifierMixin, BaseEstimator):
`

instead of 

`class IsolationForest(BaseEstimator):
`

Using PyCharm (Pro) as IDE. Just running in standard 'console' mode (i.e., not using any notebooks)

Version:
- Python: 3.12.4
- scikit: 1.5.2
- isotree: 0.6.1.post4

**Comment by david-cortes** [comment]
Thanks for the bug report. Should be fixed now:
```shell
pip install -U isotree
```
